# Generated by Django 6.0 on 2026-01-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('last_data_hash', models.CharField(max_length=255)),
                ('emailed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
