# Generated by Django 6.0 on 2026-01-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_nrbrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalMetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('fine_gold', models.IntegerField()),
                ('tejabi_gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
