# Generated by Django 6.0 on 2026-01-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0003_localmetalrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalsAPIRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(default='USD', max_length=10)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField()),
                ('rates', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
