# Generated by Django 6.0 on 2026-01-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0004_metalsapirate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('XAU', 'Gold'), ('XAG', 'Silver')], max_length=3)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('rate', models.FloatField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MetalsAPIRate',
        ),
    ]
