# Generated by Django 6.0 on 2026-01-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0005_metalrate_delete_metalsapirate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metalrate',
            old_name='rate',
            new_name='price_gram_usd',
        ),
    ]
