# Generated by Django 6.0 on 2026-01-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0006_rename_rate_metalrate_price_gram_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalRateTola_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('XAU', 'Gold'), ('XAG', 'Silver')], max_length=3)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_gram_usd', models.FloatField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
