# Generated by Django 6.0 on 2026-01-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0007_metalratetola_v2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metalratetola_v2',
            old_name='price_gram_usd',
            new_name='price_tola_npr',
        ),
    ]
