# Generated by Django 6.0 on 2026-01-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0009_ratenotificationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateNotificationLog',
        ),
    ]
