# Generated by Django 6.0 on 2026-01-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0010_delete_ratenotificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalratetola_v2',
            name='fetched_at',
            field=models.DateTimeField(),
        ),
    ]
