# Generated by Django 6.0 on 2026-01-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0011_alter_metalratetola_v2_fetched_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metalratetola_v2',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='metalratetola_v2',
            name='metal',
        ),
        migrations.RemoveField(
            model_name='metalratetola_v2',
            name='price_tola_npr',
        ),
        migrations.AddField(
            model_name='metalratetola_v2',
            name='date',
            field=models.CharField(default='Date not found', max_length=50),
        ),
        migrations.AddField(
            model_name='metalratetola_v2',
            name='fine_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalratetola_v2',
            name='silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metalratetola_v2',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
