# Generated by Django 6.0 on 2026-01-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0012_remove_metalratetola_v2_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalratetola_v2',
            name='fetched_at',
            field=models.DateTimeField(),
        ),
    ]
