# Generated by Django 6.0 on 2026-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0013_alter_metalratetola_v2_fetched_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metalratetola_v2',
            name='date',
        ),
        migrations.RemoveField(
            model_name='metalratetola_v2',
            name='fine_gold',
        ),
        migrations.RemoveField(
            model_name='metalratetola_v2',
            name='silver',
        ),
        migrations.AddField(
            model_name='metalratetola_v2',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='metalratetola_v2',
            name='metal',
            field=models.CharField(choices=[('XAU', 'Gold'), ('XAG', 'Silver')], default='XAU', max_length=3),
        ),
        migrations.AddField(
            model_name='metalratetola_v2',
            name='price_tola_npr',
            field=models.FloatField(default=0),
        ),
    ]
